name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          # LiveView 1.0 isn't compatible with 1.14.0
          - elixir: '1.14.1'
            otp: '25'
          - elixir: '1.15'
            otp: '26'
          - elixir: '1.16'
            otp: '26'
          - elixir: '1.17'
            otp: '27'
            lint: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile with warnings
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Compile without warnings
        run: mix compile

      - name: Check format
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Credo
        run: mix credo
        if: ${{ matrix.lint }}

      - name: Run tests
        run: mix test
